# Generated by Django 4.2.7 on 2024-02-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
