# Generated by Django 4.2.7 on 2024-02-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerdata', '0005_alter_customerdata_customer_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customerdata',
            new_name='customer',
        ),
    ]
