# Generated by Django 4.2.7 on 2024-02-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerdata', '0006_rename_customerdata_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer',
            new_name='customerdata',
        ),
    ]
