# Generated by Django 4.2.7 on 2024-02-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdata', '0007_rename_customer_customerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='customer_id',
            field=models.AutoField(max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
