# Generated by Django 4.2.7 on 2024-02-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdata', '0008_alter_customerdata_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='customer_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
