# Generated by Django 4.2.7 on 2024-03-01 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customerdata', '0009_alter_customerdata_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='pincode',
            field=models.IntegerField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
