# Generated by Django 4.2.7 on 2024-03-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdata', '0010_customerdata_pincode_alter_customerdata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
