# Generated by Django 4.2.7 on 2024-03-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdata', '0012_remove_customerdata_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='pincode',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
