# Generated by Django 4.2.7 on 2024-03-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdata', '0013_customerdata_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
