# Generated by Django 4.2.7 on 2024-03-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerdata', '0013_customerdata_pincode'),
        ('remainingAmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation', models.CharField(max_length=50)),
                ('advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerdata.customerdata')),
            ],
        ),
        migrations.DeleteModel(
            name='remainingAmt',
        ),
    ]
