# Generated by Django 4.2.7 on 2024-03-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
