# Generated by Django 4.2.7 on 2024-03-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='utr',
            field=models.CharField(default=1, max_length=18),
            preserve_default=False,
        ),
    ]
