# Generated by Django 4.2.7 on 2024-03-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_created_at_payment_utr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiration_date',
            field=models.IntegerField(),
        ),
    ]
