# Generated by Django 4.2.7 on 2024-03-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_decoration_image_decoration_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='customer_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
