# Generated by Django 4.2.7 on 2024-03-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_decoration_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='customization',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
