# Generated by Django 4.2.7 on 2023-12-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=50)),
                ('eventdate', models.DateField(max_length=50)),
                ('eventname', models.CharField(max_length=50)),
                ('eventvenue', models.CharField(max_length=50)),
                ('eventcity', models.CharField(max_length=50)),
                ('ant', models.CharField(max_length=50)),
                ('ad', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
            ],
        ),
    ]
